# Generated by Django 6.0.7 on 2026-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nb_personnes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('livraison', 'Livraison à domicile'), ('sur_place', 'Sur place')], default='livraison', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='commande',
            name='quartier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('prete', 'Prête à être servie'), ('livree', 'Livrée / Servie'), ('annulee', 'Annulée')], default='en_preparation', max_length=20),
        ),
    ]
