# Generated by Django 6.0.7 on 2026-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_commande_nb_personnes_commande_type_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
